[workspace]
resolver = "2"

members = [
    "juniper-from-schema",
    "juniper-from-schema-proc-macro",
    "juniper-from-schema-code-gen",
    "builder",

    # Tests
    "builder-tests/basic",
    "builder-tests/file",
]

exclude = ["generate-subscription-tests"]
