[workspace]
resolver = "2"

members = [
    "juniper-from-schema",
    "proc-macro",
    "code-gen",
    "builder",

    # Tests
    "builder-tests/basic",
    "builder-tests/file",
]

exclude = ["generate-subscription-tests"]
